### ISSUE TITLE
 请问z这是怎么了

### ISSUE THREAD

**Issue by 377123** [ExerciseBook/DiscuzQ-RouteDemo#1]
- 官方的接口

![image](https://user-images.githubusercontent.com/4208764/93293226-1302a500-f81a-11ea-99b2-7a7a9a08fc76.png)

- 你的接口
![image](https://user-images.githubusercontent.com/4208764/93293400-742a7880-f81a-11ea-8b26-fe8369178107.png)
 请问z这是怎么了

**Comment by 377123** [comment]
貌似是客户端请求问题

**Comment by ExerciseBook** [comment]
Request Headers 部分是客户端发的。
其中 Accept 头的意思是期望服务端返回什么类型的信息。理论上这里包含 application/json 就差不多了。
